arb-dir: lib/src/localization/arb
template-arb-file: app_fr.arb
output-localization-file: app_localizations.dart
nullable-getter: false
use-named-parameters: true
required-resource-attributes: true
untranslated-messages-file: untranslated_messages.json
