// ignore_for_file: unused-code
import 'package:field_service/src/common/exceptions/app_exception_code.dart';

/// Base class for all all client-side errors that can be generated by the app
sealed class AppException implements Exception {
  const AppException(this.code, this.message);
  // ignore: unused-code
  final AppExceptionCode code;
  final String message;

  @override
  String toString() => message;
}

/// Auth
class WrongPasswordException extends AppException {
  WrongPasswordException()
    : super(AppExceptionCode.wrongPassword, 'Wrong password');
}

class RequiresRecentLoginException extends AppException {
  RequiresRecentLoginException()
    : super(AppExceptionCode.requiresRecentLogin, 'Requires recent login');
}

class EmailAlreadyInUseException extends AppException {
  EmailAlreadyInUseException()
    : super(AppExceptionCode.emailAlreadyInUse, 'Email already in use');
}

class SignupException extends AppException {
  SignupException() : super(AppExceptionCode.signupException, 'Signup error');
}

class UnauthenticatedException extends AppException {
  UnauthenticatedException()
    : super(AppExceptionCode.unauthenticated, 'Unauthenticated');
}

class WeakPasswordException extends AppException {
  WeakPasswordException()
    : super(AppExceptionCode.weakPassword, 'Weak password');
}

/// Data
class DataNotFoundException extends AppException {
  DataNotFoundException([String? message])
    : super(AppExceptionCode.dataNotFound, message ?? 'Data not found');
}

/// Url Launcher
class UnsupportedUrlException extends AppException {
  UnsupportedUrlException()
    : super(AppExceptionCode.unsupportedUrl, 'Unsupported URL');
}

class LaunchUrlException extends AppException {
  LaunchUrlException()
    : super(AppExceptionCode.launchUrl, 'Error launching URL');
}

class PassageTemplateNotFoundException extends AppException {
  PassageTemplateNotFoundException()
    : super(
        AppExceptionCode.passageTemplateNotFound,
        'Passage template not found',
      );
}

class PassageNotFoundException extends AppException {
  PassageNotFoundException()
    : super(AppExceptionCode.passageNotFound, 'Passage not found');
}
