/// Flutter icons CustomIcon
/// Copyright (C) 2025 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  CustomIcon
///      fonts:
///       - asset: fonts/CustomIcon.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class CustomIcon {
  CustomIcon._();

  static const _kFontFam = 'CustomIcon';
  static const String? _kFontPkg = null;

  static const IconData floppy_disk = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData paper_plane_tilt = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData text_align_justify = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData path = IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData arrow_down_right = IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData arrow_up_right = IconData(0xe805, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData calendar = IconData(0xe806, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData image_square_2 = IconData(0xe807, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData chat = IconData(0xe808, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData chat_dots = IconData(0xe809, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData file_video = IconData(0xe80a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData file_pdf = IconData(0xe80b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData files = IconData(0xe80c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData camera_plus = IconData(0xe80d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData trash = IconData(0xe80e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData images_square = IconData(0xe80f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData pencil = IconData(0xe810, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData traffic_cone = IconData(0xe811, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData link = IconData(0xe812, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData link_break = IconData(0xe813, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData chats_teardrop = IconData(0xe814, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData clipboard_text = IconData(0xe815, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData signature = IconData(0xe816, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
